version: '3'

services:
  app:
    image: kerwin1202/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
      # 访问jwt加密参数，可选 不为空则允许登录 同时需要设置 MONGODB_URL
      AUTH_SECRET_KEY:
      # 每小时最大请求次数，可选，默认无限
      MAX_REQUEST_PER_HOUR: 0
      # 网站名称
      SITE_TITLE: ChatGpt Web
      # mongodb 的连接字符串
      MONGODB_URL: 'mongodb://chatgpt:xxxx@database:27017'
      # 开启注册之后 密码加密的盐
      PASSWORD_MD5_SALT: anysalt
      # 开启注册之后 超级管理邮箱
      ROOT_USER: xxx@qq.com
      # 网站是否开启注册 必须开启, 否则管理员都没法注册, 可后续关闭
      REGISTER_ENABLED: true
      # 更多配置, 在运行后, 注册管理员, 在管理员页面中设置
    links:
      - database

  database:
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: xxxx
      MONGO_INITDB_DATABASE: chatgpt

  mongo-gui:
    container_name: mongo-gui
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - '4321:4321'
    environment:
      - MONGO_URL=mongodb://chatgpt:xxxx@database:27017
    links:
      - database
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: chatgptweb-database
    restart: unless-stopped
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

volumes:
  mongodb: {}
